import {test} from 'node:test';import assert from 'node:assert/strict';
import * as g from '../shared/widget.mjs';import {defaults} from '../shared/model.mjs';import Controller from '../desktop/widget-controller.cjs';
const display={id:1,bounds:{x:0,y:0,width:1920,height:1080},workArea:{x:0,y:0,width:1920,height:1040}};
test('Migration ist idempotent und erhält Secret, Profile, Grenzen und Kennungen',()=>{const saved={secret:'encrypted-example',autoStart:true,bounds:{x:200,y:40,width:300,height:180},profiles:{Gaming:{locked:true,theme:'light',bounds:{x:80,y:20,width:220,height:190}}}};const c=g.migrate(saved,defaults());assert.equal(c.secret,saved.secret);assert.equal(c.autoStart,true);assert.deepEqual(c.bounds,saved.bounds);assert.equal(c.profiles.Gaming.theme,'light');assert.equal(c.profiles.Gaming.fontSize,48);assert.deepEqual(g.migrate(c,defaults()),c);});
test('Konkave Schultern: tangential, an allen Kanten, innerhalb des Fensters',()=>{for(const e of g.edges)for(const [w,h] of [[150,96],[300,120],[130,260],[800,480]])for(const amount of [0,.01,.25,.5,.75,.99,1])for(const gap of [0,18,35]){const s=g.contour(w,h,e,amount,gap);assert.ok(s.path.includes(' C '));for(const [x,y]of s.polygon){assert.ok(x>=-.001&&y>=-.001);assert.ok(x<=s.width+.001&&y<=s.height+.001);}assert.ok(g.region(s.polygon,s.width,s.height).length>0);}const p=g.contour(300,120,'top',1).points;assert.equal(p[0][1],0);assert.equal(p[1][1],0);assert.equal(p[2][0],p[3][0]);assert.ok(p[0][0]<p[1][0]);assert.equal(p[15][1],0);assert.equal(p[14][1],0);assert.ok(p[15][0]>p[14][0]);});
test('Freiform ist kantenunabhängig; Region schließt transparente Ecken aus',()=>{for(const e of g.edges){const s=g.contour(300,180,e,0);const rects=g.region(s.polygon,s.width,s.height);assert.ok(!rects.some(r=>r.x===0&&r.y===0));assert.ok(rects.some(r=>r.x<=150&&r.x+r.width>=150&&r.y<=90&&r.y+r.height>=90));}});
test('Andockzone, Monitorübergänge, Taskleisten- und Auto-Hide-Abstand',()=>{let b={x:500,y:15,width:250,height:140};assert.equal(g.nearest(b,display,[display]).edge,'top');assert.equal(g.nearest({...b,y:17},display,[display]),null);const peer={id:2,bounds:{x:1920,y:0,width:1920,height:1080},workArea:{x:1920,y:0,width:1920,height:1040}};assert.equal(g.nearest({x:1670,y:500,width:250,height:140},display,[display,peer]),null);const t=g.dockTarget(b,display,'bottom');assert.equal(t.y+t.height,1040);const hidden={...display,workArea:display.bounds,autoHideEdges:['bottom']};assert.equal(g.boundary(hidden).height,1078);const bar=g.taskbarBounds(hidden);assert.ok(bar.y+bar.height<1078);});
test('Ausrichtung nutzt Hysterese; gemessene Schrift bestimmt Mindestmaß',()=>{const c={alignment:'auto'};assert.equal(g.orientation(c,{width:100,height:100},'horizontal'),'horizontal');assert.equal(g.orientation(c,{width:100,height:100},'vertical'),'vertical');assert.equal(g.orientation(c,{width:80,height:100},'horizontal'),'vertical');assert.equal(g.orientation(c,{width:120,height:100},'vertical'),'horizontal');for(const layout of ['horizontal','vertical']){const min=g.minimum(48,layout,{number:120,trend:40,label:170});assert.ok(min.width>=214);assert.ok(min.height>=120);}});
function fixture(edge){let cursor={x:700,y:500},c=g.migrate({},defaults());c.bounds=g.dockTarget({x:600,y:350,width:250,height:160},display,edge);c.dock={edge,monitor:1};const messages=[];const win={webContents:{on(){},send(t,f){messages.push(f);}},on(){},isDestroyed(){return false},getBounds(){return c.bounds},setBounds(){},setShape(){},setResizable(){},setMovable(){},setIgnoreMouseEvents(){},setAlwaysOnTop(){}};const controller=new Controller(win,{geometry:g,screen:{getCursorScreenPoint:()=>cursor,getDisplayMatching:()=>display},config:()=>c,save(){},displays:()=>[display]});return {c,controller,move:(dx,dy)=>{cursor={x:700+dx,y:500+dy}},messages};}
test('Alle vier Kanten: Inhalt folgt sofort; Hals bildet sich ohne Sprung zurück',()=>{for(const edge of g.edges){const f=fixture(edge),w=f.controller,start={...w.b};w.start('drag');const dx=edge==='left'?18:edge==='right'?-18:0,dy=edge==='top'?18:edge==='bottom'?-18:0;f.move(dx,dy);w.move();assert.equal(w.b.x,start.x+dx);assert.equal(w.b.y,start.y+dy);assert.equal(w.amount,.5);assert.equal(w.gap,18);f.move(dx/2,dy/2);w.move();assert.equal(w.amount,.75);f.move(dx*3,dy*3);w.move();assert.equal(w.amount,0);assert.equal(f.c.dock,null);w.cancel();}});
test('Reduzierte Bewegung erreicht dieselbe Endform; Schrift hält Kontaktkante fest',()=>{for(const edge of g.edges){const f=fixture(edge),w=f.controller;f.c.reduceMotion=true;const target=g.dockTarget(w.b,display,edge);w.animate(target,1,edge);assert.equal(w.amount,1);assert.equal(w.animation,null);f.c.fontSize=110;w.apply();const expected=g.dockTarget(w.b,display,edge);assert.deepEqual(w.b,expected);w.cancel();}});
test('Unterbrochene Andockanimation setzt vom aktuellen Zustand fort',async()=>{const f=fixture('top'),w=f.controller;w.amount=.2;w.animate({...w.b,y:0},1,'top');await new Promise(r=>setTimeout(r,70));const amount=w.amount,b={...w.b};assert.ok(amount>.2&&amount<1);w.start('drag');assert.equal(w.amount,amount);assert.deepEqual(w.b,b);await new Promise(r=>setTimeout(r,35));assert.deepEqual(w.b,b);w.cancel();});
