import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {arrows,format,category,freshness,widgetDelta} from '../shared/model.mjs';
import {contour,padding,orientation} from '../shared/widget.mjs';
export function Widget({state,act,now,embedded=false,taskbar=false}:any){
 const c=state.config,ref=useRef<HTMLElement>(null),gesture=useRef(false),[size,setSize]=useState({width:260,height:150}),[frame,setFrame]=useState(state.widgetFrame),[layout,setLayout]=useState('horizontal');
 const f=freshness(state.feed.entries,now,c.staleMinutes),v=f.last?.value,change=widgetDelta(state.feed.entries,c.unit,now,c.staleMinutes);
 useLayoutEffect(()=>{const e=ref.current;if(!e)return;const ro=new ResizeObserver(([entry])=>{setSize({width:entry.contentRect.width,height:entry.contentRect.height});});ro.observe(e);return()=>ro.disconnect();},[]);
 useEffect(()=>{if(embedded||taskbar)return;setFrame(state.widgetFrame);return window.nebel?.onWidgetFrame(setFrame);},[embedded,taskbar]);
 useEffect(()=>{setLayout(old=>orientation(c,size,old,embedded?null:c.dock?.edge));},[size,c.alignment,c.dock?.edge]);
 useEffect(()=>{if(embedded||taskbar||!window.nebel)return;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d')!;ctx.font=`650 ${c.fontSize}px "Segoe UI", sans-serif`;let number=Math.max(...['888','600','33,3','—'].map(s=>ctx.measureText(s).width));ctx.font=`550 ${Math.max(12,c.fontSize*.32)}px "Segoe UI", sans-serif`;number+=Math.max(...[' (+580)',' (−580)',' (+32,2)',' (±0,0)'].map(s=>ctx.measureText(s).width));ctx.font=`500 ${c.fontSize*.55}px "Segoe UI", sans-serif`;const trend=Math.max(...Object.values(arrows).map((s:any)=>ctx.measureText(s).width));ctx.font=`500 ${Math.max(11,c.fontSize*.22)}px "Segoe UI", sans-serif`;const label=Math.max(...['999 Min. · veraltet','−580 mg/dL · Demo','−32,2 mmol/L · Demo','Verbindung fehlt','Keine Messung'].map(s=>ctx.measureText(s).width));act('widget-measure',{number,trend,label});},[c.fontSize,embedded,taskbar]);
 useEffect(()=>{if(embedded||taskbar)return;const mq=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>act('widget-motion',{reduced:mq.matches});update();mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update);},[embedded,taskbar]);
 const active=frame&&!embedded&&!taskbar?frame:null,p=padding(size.width,size.height),shape=active||contour(size.width,size.height,null),body=active?.body||{left:p,top:p,width:size.width-2*p,height:size.height-2*p};
 const age=f.last?`${f.minutes} Min.${f.stale?' · veraltet':state.feed.error?' · offline':state.feed.future?' · Zeitfehler':''}`:'Keine Messung';
 const trend=f.stale?'':arrows[f.last?.trend]||'·';
 const start=(e:React.PointerEvent)=>{if(embedded||taskbar||c.locked||c.clickThrough||e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);gesture.current=true;const edge=(e.target as HTMLElement).dataset.edge;act(edge?'resize-start':'drag-start',edge?{edge}:{});};
 const end=()=>{if(gesture.current){gesture.current=false;act('gesture-end');}};
 if(taskbar)return <main className={'taskbar-reading '+(v==null?'':category(v))} aria-label="Anzeige an der Taskleiste"><strong>{format(v,c.unit)}</strong><span>{trend}</span><span className="taskbar-unit">{c.unit}</span><span className={'taskbar-time '+(f.stale?'warning':'')}>· {f.last?new Date(f.last.time).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'—'}{f.stale?' · veraltet':state.feed.error?' · offline':''}{c.source==='demo'?' · Demo':''}</span></main>;
 return <main ref={ref} className={`haze-widget ${c.surface} text-${['light','dark'].includes(c.widgetText)?c.widgetText:'auto'} ${state.highContrast?'high-contrast':''} ${embedded?'embedded':''} ${c.locked?'locked':''}`} style={{'--value-size':`${c.fontSize}px`,'--time-size':`${Math.max(11,c.fontSize*.22)}px`,'--glass-opacity':c.glassOpacity} as React.CSSProperties} onPointerDown={start} onPointerMove={()=>{if(gesture.current)act('gesture-move');}} onPointerUp={end} onLostPointerCapture={end}>
  <svg className="widget-surface" width="100%" height="100%" viewBox={`0 0 ${shape.width} ${shape.height}`} aria-hidden="true"><path d={shape.path} className="surface-base"/></svg>
  <div className={`widget-content ${active?.layout||layout} ${v==null?'':category(v)}`} style={{left:body.left,top:body.top,width:body.width,height:body.height}}>
   <div className="widget-number">{format(v,c.unit)}<span className="widget-delta-inline" aria-label={change?.description||'Änderung nicht verfügbar'}>({change?.text||'—'})</span></div><div className="widget-trend" aria-label={f.stale?'Trend veraltet':f.last?.trend?'Trend '+f.last.trend:'Trend unbekannt'}>{trend}</div>
   <div className="widget-meta"><span className="widget-unit-line"><span>{c.unit}{c.source==='demo'?' · Demo':''}</span></span><span className={f.stale?'warning':''} role="status">{age}</span></div>
  </div>
  {!embedded&&!c.locked&&!c.clickThrough&&<div className="widget-handles" style={{left:body.left,top:body.top,width:body.width,height:body.height}}>{['n','s','e','w','ne','nw','se','sw'].map(edge=><div key={edge} data-edge={edge} className={'resize-edge '+edge}/>)}</div>}
 </main>;
}
